export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  design: (id: string) => `/design/${id}`,
  studio: (username: string) => `/studio/${username}`,
  artist: (handle: string) => `/artist/${handle}`,
  portfolio: (id: string) => `/portfolio/${id}`,
  collection: (id: string) => `/collection/${id}`,
  gallery: '/gallery',
  skills: '/skills',
  jobs: '/jobs',
  job: (id: string) => `/jobs/${id}`,
  jobPost: '/jobs/post',
  search: '/search',
  dashboard: '/dashboard',
  dashboardAnalytics: '/dashboard/analytics',
  dashboardUploads: '/dashboard/uploads',
  dashboardEarnings: '/dashboard/earnings',
  dashboardSettings: '/dashboard/settings',
  dashboardJobs: '/dashboard/jobs',
  dashboardListings: '/dashboard/listings',
  dashboardMessages: '/dashboard/messages',
  dashboardWishlist: '/dashboard/wishlist',
  dashboardSkills: '/dashboard/skills',
} as const;
