export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  design: (id: string) => `/design/${id}`,
  studio: (username: string) => `/studio/${username}`,
  artist: (handle: string) => `/artist/${handle}`,
  portfolio: (id: string) => `/portfolio/${id}`,
  gallery: '/gallery',
  skills: '/skills',
  jobs: '/jobs',
  job: (id: string) => `/jobs/${id}`,
  dashboard: '/dashboard',
  dashboardUploads: '/dashboard/uploads',
  dashboardEarnings: '/dashboard/earnings',
  dashboardSettings: '/dashboard/settings',
} as const;
